services:
  - type: web
    name: xscard-enterprise-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build:prod
    staticPublishPath: frontend/dist
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

